FROM nginx:stable-alpine

ADD ozp-center.tar.gz /usr/share/nginx/html/center
ADD ozp-hud.tar.gz /usr/share/nginx/html/hud
ADD ozp-webtop.tar.gz /usr/share/nginx/html/webtop
ADD ozp-iwc.tar.gz /usr/share/nginx/html/iwc
ADD ozp-help.tar.gz /usr/share/nginx/html/help
